name: Bug report
description: Report a bug
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug and expected result
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to Reproduce
      description: Step-by-step including inputs/URLs/commands
      placeholder: |
        1.
        2.
        3.
  - type: textarea
    id: logs
    attributes:
      label: Logs & Screenshots
